### ISSUE TITLE
Support writing code to different modules

### ISSUE THREAD

**Issue by weixsun** [alibaba/cloud-native-app-initializer#26]
CN:
当选择一个dependency时，能够支持按照模块后缀名分别写入不同模块中，下面是一个简单说明示例：

```yaml
    - name: Web
      content:
        - name: Spring Web
          id: web
          description: xxx
          archCfg:
            mvc:
              modules:
                web:
                  code: true
                service:
                  code: true
                start:
                  code: false
```

```
./
├── web
│   ├── java
│   │   └── Xxx.java.mustache
│   └── resources
│       ├── application.properties.mustache
│       └── log4j.properties.mustache
├── service
│   └── java
│       └── Yyy.java.mustache
└── start
    ├── java
    │   ├── Zzz.java.mustache
    └── resources
        ├── application.properties.mustache
        └── log4j.properties.mustache
```

结果：选择Spring Web 依赖时，会向web 和 service模块写入相应代码，start 模块因为`code: false`而不写入模版目录下的start 代码。
